### ISSUE TITLE
Wrong modal iframe heigth

### ISSUE THREAD

**Issue by geraldcloudnine** [storyblok/field-plugin#332] opened 2024-01-11 10:01 UTC
**Describe the bug**
The height of the iframe doesn't fill the available height of the modal.

**To Reproduce**
1. Create a new field plugin running `npx @storyblok/field-plugin-cli@latest create`
2. Select React (I don't think it matters, but only tested with the React template)
4. Run `pnpm dev`
5. Open sandbox
6. Open modal.

**Expected behavior**
The iframe should fill the available height.

**Screenshots**
![image](https://github.com/storyblok/field-plugin/assets/97538197/4d0a2b18-61e6-42de-a209-5eb68eeb08c6)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Edge & Chrome
 - Version 120.0.2210.121 (Official build) (arm64) - Edge browser

**Comment by eunjae-lee** [comment] 2024-01-11 10:43
Hi @geraldcloudnine. Thanks for reaching out to us.

I just followed your instruction, and I couldn't reproduce the issue. Could you check which version of `@storyblok/field-plugin` you're using in your package.json?

**Comment by geraldcloudnine** [comment] 2024-01-11 10:57
Hi @eunjae-lee. Thanks for looking into this.

I am using  "@storyblok/field-plugin": "1.0.1".

I tested again in the sandbox and seems to work there, but not when I load it in the plugin editor (see video). The issue is also present on another plugin we currently have live at my company. 

![Screen Recording 2024-01-11 at 11 53 18 (1)](https://github.com/storyblok/field-plugin/assets/97538197/050b8d67-b6c6-4f02-8eba-5565044b4776)

**Comment by eunjae-lee** [comment] 2024-01-11 14:09
Hi @geraldcloudnine , we've identified the issue on our end. We're working on the fix right now, and as soon as it's released, it should be fine on your end. No action is required from you. Sorry for the inconvenience, and I will keep you updated soon.

**Comment by eunjae-lee** [comment] 2024-01-11 22:05
Hi @geraldcloudnine This should be fixed now. Thanks for your patience.

**Closed by eunjae-lee** 2024-01-11 22:05 UTC

**Comment by geraldcloudnine** [comment] 2024-01-12 09:29
Thanks @eunjae-lee, it works great now :)
