### ISSUE TITLE
Vue3 Template - Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/field-plugin#107] opened 2023-04-02 20:27 UTC
**Describe the bug**
When trying to run a vue3 plugin, it results in an error.
![image](https://user-images.githubusercontent.com/5083273/229377279-3770ad4c-afe4-4c63-9a18-c77add9c0bfe.png)

**To Reproduce**
1. Run `npx @storyblok/field-plugin-cli@alpha`
2. Go into the new field plugin project with `cd {what-ever-you-named-it}`
3. Run `yarn build`
4. CHeck the errors

**Expected behavior**
I expect no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/5083273/229377279-3770ad4c-afe4-4c63-9a18-c77add9c0bfe.png)
![image](https://user-images.githubusercontent.com/5083273/229377264-086a9638-6208-4533-bc05-b3a30cc28d82.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 111.0.5563.111

**Additional context**
I have no idea if this actually causes it to not work properly, or if its just an error with no affect.

**Comment by nachoadjust** [comment] 2023-04-16 13:15
Did you get it to work locally or does it also fail there?
I just installed the vue3 example and I am automatically getting an error: `The window is not embedded within another window`, when running it locally (yarn dev)

**Comment by johannes-lindgren** [comment] 2023-04-17 18:47
Hi @SebbeJohansson, thanks for reporting this issue. This is actually the expected behavior. This error occurs because the legacy `fieldtype-wrapper.js` script is still present in the field plugin's document. This script fails because it expects a Vue 2 component in a certain global variable. We plan to remove this script from the document, which will make the error vanish. Nevertheless, I will keep this issue open until we have addressed that issue.

**Comment by SebbeJohansson** [comment] 2023-04-17 18:50
@johannes-lindgren Aaaah okay interesting! Might be worth it to add that to the documentation so that its more clear. Not sure if this issue is clear enough. 🤔

**Comment by johannes-lindgren** [comment] 2023-04-25 15:05
@SebbeJohansson I have merged pull request #140 that replaces the error you've spotted with a different error that should be more clear. There will still be an error in the console, but it should be clear that the app is fully functional:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/14206504/234320117-cbc90cf2-1e2a-4620-839d-07735ab926b6.png">

That is the best we can do at the moment. I will still keep this ticket open until we have a permanent solution.

**Comment by SebbeJohansson** [comment] 2023-04-26 20:35
Looks good! Thanks!

**Comment by PTiCA1** [comment] 2023-09-18 17:45
I also have a problem with starting the project. I installed the latest version today and it gives me an error:
`This error can be safely ignored. It is caused by the legacy field plugin API. See issue https://github.com/storyblok/field-plugin/issues/107`

Isn't there a hotfix?

<img width="1285" alt="Snímek obrazovky 2023-09-18 v 19 42 01" src="https://github.com/storyblok/field-plugin/assets/7615801/c777a6d7-0fcd-49aa-8486-6fbed81e8881">

**Comment by eunjae-lee** [comment] 2023-09-19 09:03
fixed by #140

**Closed by eunjae-lee** 2023-09-19 09:03 UTC
